# Bixing Technology Website Configuration
title: Bixing Technology
description: AI Education, Custom Solutions Development, and Enterprise Consultation services
baseurl: "/bixingai-web"
url: "https://bixoryai.github.io"

# Build settings for blog posts
markdown: kramdown
permalink: /insights/:title/

# Default front matter for blog posts only
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bixing Team"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - starting-info.md
  - "Project Requirement Document.md"

# Required plugin for blog feed
plugins:
  - jekyll-feed
