# Development-specific configuration
# This file is loaded in addition to _config.yml when using the development build

# Use a different URL for development
url: ""
baseurl: ""

# Enable more detailed output for debugging
verbose: true

# Disable some production optimizations
compress_html:
  enabled: false

# Add any development-specific settings below
livereload: true
incremental: true
